apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: nginx-http-route
  namespace: applications
  labels:
    app: nginx
spec:
  parentRefs:
  - name: shared-gateway
    namespace: admin
  # hostnames:
  # - "nginx.noama"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /nginx
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: nginx
      port: 80
